export const PROSTATE_FORM: object = {
  pages: [
    {
      name: 'caseInformation',
      title: 'Case Information',
      elements: [
        { type: 'text', name: 'caseNumber', title: 'Case Number' },
        { type: 'text', name: 'patientName', title: 'Name' },
        { type: 'text', name: 'ageSex', title: 'Age/Sex' },
        { type: 'text', name: 'doctorName', title: 'Name of the doctor' },
      ],
    },
    {
      name: 'clinicalDetails',
      title: '1. Clinical Details',
      elements: [
        { type: 'text', name: 'clinicalPsa', title: 'PSA' },
        { type: 'text', name: 'clinicalFreePsa', title: 'Free PSA' },
        { type: 'text', name: 'clinicalFreeToTotalPsaRatio', title: 'Free to Total PSA Ratio' },
        { type: 'comment', name: 'clinicalBiopsy', title: 'Biopsy' },
        { type: 'comment', name: 'clinicalTreatmentHistory', title: 'Treatment History' },
        { type: 'comment', name: 'clinicalBoneScan', title: 'Bone Scan' },
      ],
    },
    {
      name: 'technique',
      title: '2. Technique',
      elements: [
        { type: 'text', name: 'techniqueModalityMri', title: 'Modality-MRI', defaultValue: 'MRI' },
        {
          type: 'radiogroup',
          name: 'techniqueFieldStrength',
          title: 'Field Strength',
          choices: ['0.1', '1', '1.5', '3'],
        },
        {
          type: 'radiogroup',
          name: 'techniqueIvContrast',
          title: 'IV Contrast',
          choices: ['Yes', 'No'],
        },
        {
          type: 'radiogroup',
          name: 'techniquePiqual',
          title: 'PIQUAL',
          choices: ['1', '2', '3', '4', '5'],
        },
      ],
    },
    {
      name: 'comparison',
      title: '3. Comparison',
      elements: [
        { type: 'text', name: 'comparisonDocumentDate', title: 'Date of Document', inputType: 'date' },
        { type: 'text', name: 'comparisonModality', title: 'Modality of comparison study' },
      ],
    },
    {
      name: 'findingsProstateSeminalVessels',
      title: '4. Findings - Prostate and Seminal Vessels',
      elements: [
        {
          type: 'radiogroup',
          name: 'findingsHemorrhage',
          title: 'Hemorrhage',
          choices: ['Yes', 'No'],
        },
        { type: 'text', name: 'findingsProstateSize', title: 'Prostate Size (cm)' },
        { type: 'text', name: 'findingsProstateVolume', title: 'Prostate Volume CC' },
        { type: 'text', name: 'findingsPsaDensity', title: 'PSA Density' },
        {
          type: 'paneldynamic',
          name: 'lesions',
          title: 'Lesions',
          minPanelCount: 0,
          maxPanelCount: 4,
          panelAddText: 'Add lesion',
          panelRemoveText: 'Remove lesion',
          templateElements: [
            { type: 'text', name: 'lesionSize', title: 'Size' },
            {
              type: 'radiogroup',
              name: 'lesionT2SignalIntensity',
              title: 'T2 Signal Intensity',
              choices: ['Hyperintense', 'Hypointense', 'Mixed'],
            },
            {
              type: 'radiogroup',
              name: 'lesionT2Homogeneity',
              title: 'T2 Homogeneity',
              choices: ['Heterogeneous', 'Homogeneous'],
            },
            {
              type: 'radiogroup',
              name: 'lesionT2Margins',
              title: 'T2 Margins',
              choices: ['Circumscribed', 'Non-Circumscribed'],
            },
            {
              type: 'checkbox',
              name: 'lesionT2Shape',
              title: 'T2 Shape',
              choices: ['Round', 'Lentiform', 'Circumscribed', 'Wedge', 'Linear'],
            },
            {
              type: 'radiogroup',
              name: 'lesionDwiScore',
              title: 'DWI Score',
              choices: ['1', '2', '3', '4', '5'],
            },
            { type: 'text', name: 'lesionAdcValue', title: 'ADC Value' },
            {
              type: 'radiogroup',
              name: 'lesionCeMri',
              title: 'CE-MRI',
              choices: [
                'Contemporaneous (enhances at the same time as rest of prostate)',
                'Non contemporaneous (enhancement does not follow rest of prostate)',
              ],
            },
            {
              type: 'checkbox',
              name: 'lesionLocalExtent',
              title: 'Local Extent',
              choices: ['Capsule', 'NVB', 'Urethra', 'Seminal Vesicles', 'Ejaculatory Ducts', 'Pelvic side wall muscles', 'Bladder', 'Rectum', 'Penile Crura'],
            },
            {
              type: 'checkbox',
              name: 'lesionLocation',
              title: 'Location',
              choices: ['Base', 'Midgland', 'Apex'],
            },
            {
              type: 'checkbox',
              name: 'lesionMriZonalLocation',
              title: 'MRI Zonal Location',
              choices: ['PZ', 'CZ', 'TZ'],
            },
            {
              type: 'checkbox',
              name: 'lesionSectoralLocation',
              title: 'Sectoral Location',
              choices: ['L posteromedial PZ', 'L posterolateral PZ', 'L anterior PZ', 'R posteromedial PZ', 'R posterolateral PZ', 'R anterior PZ', 'L posterior TZ', 'L anterior TZ', 'R posterior TZ', 'R anterior TZ', 'Anterior fibromuscular zone', 'Central zone', 'Periurethral zone'],
            },
            {
              type: 'checkbox',
              name: 'lesionSecondLocalExtent',
              title: 'Second Local Extent',
              choices: ['Capsule', 'NVB', 'Urethra', 'Seminal Vesicles', 'Ejaculatory ducts', 'Pelvic Side wall muscles', 'Bladder', 'Rectum', 'Penile', 'Crura'],
            },
          ],
        },
        {
          type: 'radiogroup',
          name: 'findingsNodes',
          title: 'Nodes',
          choices: ['Present', 'Absent'],
        },
        {
          type: 'radiogroup',
          name: 'findingsNodeLaterality',
          title: 'Node laterality',
          visibleIf: "{findingsNodes} = 'Present'",
          choices: ['Left', 'Right', 'Bilateral'],
        },
        {
          type: 'radiogroup',
          name: 'findingsMetastases',
          title: 'Metastases',
          choices: ['Present', 'Absent'],
        },
        {
          type: 'checkbox',
          name: 'findingsMetastaticSites',
          title: 'Metastatic sites',
          visibleIf: "{findingsMetastases} = 'Present'",
          choices: ['Bone', 'Lung', 'Liver', 'Other'],
        },
        {
          type: 'text',
          name: 'findingsOtherMetastaticSite',
          title: 'Other metastasis site',
          visibleIf: "{findingsMetastaticSites} contains 'Other'",
        },
        {
          type: 'radiogroup',
          name: 'findingsHydronephrosis',
          title: 'Hydronephrosis',
          choices: ['Yes', 'No'],
        },
        {
          type: 'radiogroup',
          name: 'findingsUpperTractInfection',
          title: 'Concurrent signs upper tract infection',
          choices: ['Yes', 'No'],
        },
        { type: 'comment', name: 'findingsOtherSignificant', title: 'Other Significant Findings' },
      ],
    },
    {
      name: 'impression',
      title: '5. Impression',
      elements: [
        { type: 'text', name: 'impressionProstateVolume', title: 'Volume of Prostate' },
        { type: 'text', name: 'impressionPsaDensity', title: 'PSA Density' },
        {
          type: 'radiogroup',
          name: 'impressionPirads',
          title: 'PIRADS',
          choices: [
            '1 - Very low (clinically significant cancer is highly unlikely to be present)',
            '2 - Low (clinically significant cancer is unlikely to be present)',
            '3 - Intermediate (the presence of clinically significant cancer is equivocal)',
            '4 - High (clinically significant cancer is likely to be present)',
            '5 - Very high (clinically significant cancer is highly likely to be present)',
          ],
        },
        {
          type: 'checkbox',
          name: 'impressionSuggestedBiopsySite',
          title: 'Suggested Site for Targeted Biopsy',
          choices: ['Base', 'Midgland', 'Apex'],
        },
        {
          type: 'checkbox',
          name: 'impressionMriZonalLocation',
          title: 'MRI Zonal Location',
          choices: ['PZ', 'CZ', 'TZ'],
        },
        {
          type: 'radiogroup',
          name: 'impressionTStage',
          title: 'T Stage',
          choices: ['T0', 'T1', 'T2', 'T3a', 'T3b', 'T4'],
        },
        {
          type: 'radiogroup',
          name: 'impressionNStage',
          title: 'N Stage',
          choices: ['N0', 'N1'],
        },
        {
          type: 'radiogroup',
          name: 'impressionMStage',
          title: 'M Stage',
          choices: ['M0', 'M1a', 'M1b', 'M1c'],
        },
        {
          type: 'radiogroup',
          name: 'impressionMetastaticDisease',
          title: 'Metastatic Disease',
          choices: ['Oligo metastatic- Less than 5 metastases', 'Polymetastatic'],
        },
      ],
    },
  ],
}
