import { readViewerSettings } from './viewerSettings'
import type { Case } from './types'

const seed: Case[] = [
  {
    id: 'c1',
    patientName: 'Anil Sharma',
    sex: 'M',
    age: 67,
    mrn: 'MRN-201884',
    caseId: 'RAD-001',
    studyRegion: 'Brain',
    requisitionNo: 'NCG-2024-00041',
    dept: 'Radiology',
    diseaseType: 'Brain',
    dmg: 'Neuro-Oncology',
    center: 'NCG Chandigarh',
    referring: 'Dr. Ramesh Menon',
    studyDate: '2024-06-12',
clinicalHistory: 'Two-week history of worsening headaches with focal neurology; referred for primary-brain-tumour workup.',
    priority: 'STAT',
    status: 'In Progress',
    reportCategory: 'Provisional',
    hospital: 'PGIMER Chandigarh',
    tatPercent: 62,
    isEmergency: false,
    isCritical: false,
    aiFindingCount: 3,
    scanUrl: 'C:\\Users\\THOUGHTCLAN\\Downloads\\000001.dcm',
  },
  {
    id: 'c2',
    patientName: 'Meera Iyer',
    sex: 'F',
    age: 54,
    mrn: 'MRN-371102',
    caseId: 'RAD-002',
    studyRegion: 'Chest / Abdomen',
    requisitionNo: 'NCG-2024-00042',
    dept: 'Radiology',
    diseaseType: 'Breast',
    dmg: 'Breast Oncology',
    center: 'NCG Delhi',
    referring: 'Dr. Sunita Rao',
    studyDate: '2024-06-11',
    clinicalHistory: 'Palpable hard lump in the right upper quadrant with skin tethering; baseline staging study.',
    priority: 'Urgent',
    status: 'In Review',
    reportCategory: 'Provisional',
    hospital: 'AIIMS New Delhi',
    tatPercent: 88,
    isEmergency: false,
    isCritical: true,
    aiFindingCount: 5,
    scanUrl: 'C:\\Users\\THOUGHTCLAN\\Downloads\\000001.dcm',
  },
  {
    id: 'c3',
    patientName: 'Rajesh Kumar',
    sex: 'M',
    age: 45,
    mrn: 'MRN-120975',
    caseId: 'RAD-003',
    studyRegion: 'Head & Neck',
    requisitionNo: 'NCG-2024-00043',
    dept: 'Pathology',
    diseaseType: 'Neck',
    dmg: 'Head & Neck Oncology',
    center: 'NCG Mumbai',
    referring: 'Dr. Arvind Joshi',
    studyDate: '2024-06-10',
    clinicalHistory: 'Hoarseness and a right-sided neck mass; fine-needle aspiration for cytology.',
    priority: 'Urgent',
    status: 'Pending',
    reportCategory: 'Provisional',
    hospital: 'TMH Mumbai',
    tatPercent: 74,
    isEmergency: true,
    isCritical: false,
    aiFindingCount: null,
    slideUrl: 'C:\\Users\\THOUGHTCLAN\\Downloads\\000001.svs',
  },
  {
    id: 'c4',
    patientName: 'Sunita Verma',
    sex: 'F',
    age: 61,
    mrn: 'MRN-554098',
    caseId: 'RAD-004',
    studyRegion: 'Prostate',
    requisitionNo: 'NCG-2024-00044',
    dept: 'Pathology',
    diseaseType: 'Prostate',
    dmg: 'Genitourinary Pathology',
    center: 'NCG Mumbai',
    referring: 'Dr. Kavita Desai',
    studyDate: '2024-06-09',
    clinicalHistory: 'Elevated PSA and abnormal DRE; transrectal biopsy core evaluation.',
    priority: 'Routine',
    status: 'Completed',
    reportCategory: 'Final',
    hospital: 'TMH Mumbai',
    tatPercent: 100,
    isEmergency: false,
    isCritical: false,
    aiFindingCount: 1,
    slideUrl: 'C:\\Users\\THOUGHTCLAN\\Downloads\\000001.svs',
  },
  {
    id: 'c5',
    patientName: 'Aman Gupta',
    sex: 'M',
    age: 30,
    mrn: 'MRN-208833',
    caseId: 'RAD-005',
    studyRegion: 'Cervical Spine',
    requisitionNo: 'NCG-2024-00045',
    dept: 'Radiology',
    diseaseType: 'Skin',
    dmg: 'Ortho-Oncology',
    center: 'NCG Delhi',
    referring: 'Dr. Naveen Bhat',
    studyDate: '2024-06-08',
    clinicalHistory: 'Painful lytic lesion in the cervical spine; staging for suspected skeletal metastasis.',
    priority: 'Routine',
    status: 'Completed',
    reportCategory: 'Final',
    hospital: 'AIIMS New Delhi',
    tatPercent: 132,
    isEmergency: false,
    isCritical: false,
    aiFindingCount: 2,
    scanUrl: 'C:\\Users\\THOUGHTCLAN\\Downloads\\000001.dcm',
  },
  {
    id: 'c6',
    patientName: 'Priya Nair',
    sex: 'F',
    age: 48,
    mrn: 'MRN-697741',
    caseId: 'RAD-006',
    studyRegion: 'Breast',
    requisitionNo: 'NCG-2024-00046',
    dept: 'Radiology',
    diseaseType: 'Breast',
    dmg: 'Breast Oncology',
    center: 'NCG Delhi',
    referring: 'Dr. Sunita Rao',
    studyDate: '2024-06-11',
    clinicalHistory: 'Palpable hard lump in the right upper quadrant with skin tethering; baseline staging study.',
    priority: 'STAT',
    status: 'In Progress',
    reportCategory: 'Provisional',
    hospital: 'PGIMER Chandigarh',
    tatPercent: 41,
    isEmergency: true,
    isCritical: true,
    aiFindingCount: 7,
    scanUrl: 'C:\\Users\\THOUGHTCLAN\\Downloads\\000001.dcm',
  },
  {
    id: 'c7',
    patientName: 'Vikram Singh',
    sex: 'M',
    age: 52,
    mrn: 'MRN-442156',
    caseId: 'RAD-007',
    studyRegion: 'Abdomen / Pelvis',
    requisitionNo: 'NCG-2024-00047',
    dept: 'Pathology',
    diseaseType: 'Skin',
    dmg: 'Dermatopathology',
    center: 'NCG Delhi',
    referring: 'Dr. Naveen Bhat',
    studyDate: '2024-06-07',
    clinicalHistory: 'Excisional biopsy of a changing pigmented lesion; histopathology for staging.',
    priority: 'Urgent',
    status: 'In Review',
    reportCategory: 'Final',
    hospital: 'AIIMS New Delhi',
    tatPercent: 96,
    isEmergency: false,
    isCritical: false,
    aiFindingCount: 4,
    slideUrl: 'C:\\Users\\THOUGHTCLAN\\Downloads\\000001.svs',
  },
  {
    id: 'c8',
    patientName: 'Kavita Reddy',
    sex: 'F',
    age: 39,
    mrn: 'MRN-981220',
    caseId: 'RAD-008',
    studyRegion: 'Brain & Spine',
    requisitionNo: 'NCG-2024-00048',
    dept: 'Pathology',
    diseaseType: 'Neck',
    dmg: 'Neuropathology',
    center: 'NCG Mumbai',
    referring: 'Dr. Ramesh Menon',
    studyDate: '2024-06-06',
    clinicalHistory: 'Post-operative specimen from a neck dissection; margin and lymph-node assessment.',
    priority: 'Routine',
    status: 'Pending',
    reportCategory: 'Provisional',
    hospital: 'TMH Mumbai',
    tatPercent: 68,
    isEmergency: false,
    isCritical: false,
    aiFindingCount: null,
    slideUrl: 'C:\\Users\\THOUGHTCLAN\\Downloads\\000001.svs',
  },
]

export function getCases(): Case[] {
  const { weasisPath, qupathPath } = readViewerSettings()
  return seed.map(c => {
    if (weasisPath && c.scanUrl) return { ...c, scanUrl: weasisPath }
    if (qupathPath && c.slideUrl) return { ...c, slideUrl: qupathPath }
    return c
  })
}
